PREFIX schema: <http://schema.org/>
PREFIX ex: <http://example.org/>

insert {
   ?event ex:hasScore ?EventScore .
   ?EventScore a ex:Score;
    ex:scoreTotal ?totalScore;
    ex:scoreEventName ?name;
    ex:scoreBreakdown [
      schema:startDate  ?startDateScore 
    ]
  
  
}
where {
  ?event a schema:Event .
  BIND(URI(CONCAT(str(?event),"#Score")) as ?EventScore)
  # BIND(0 as ?totalScore)
 


  OPTIONAL {
    ?event schema:startDate ?startDate .
    FILTER(regex(str(?startDate), "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"))
    BIND(10 as ?startDateScore)
  }
   OPTIONAL {
    ?event schema:startDate ?startDate .
    FILTER(regex(str(?startDate), "^[0-9]{4}-[0-9]{2}-[0-9]{2}T.*$"))
    BIND(20 as ?startDatescore)
  }

   OPTIONAL {
    ?event schema:name ?name ; schema:location ?location ; schema:startDate ?startDate .
    BIND(?startDate + 100 as ?totalScore)
  }
}