name: Score agoradanse.com Events

on:
  workflow_dispatch:
      
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/generate-report.yml
    with:
        page_url: "https://agoradanse.com/evenement/"
        entity_identifier: "a.event-active"
        file_name: "agoradanse-com.jsonld"
        is_paginated: "false"
        headless: "false"
