name: Score agoradanse.com Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
      
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/generate_report.yml
    with:
        page_url: "https://agoradanse.com/evenement/montreal-marrakech/?utm_source=fb&utm_medium=Facebook_Mobile_Feed&utm_campaign=120211877123720753&fbclid=IwZXh0bgNhZW0BMAABHToAQwEUL2gvJgRPRTTbIXvTlaiA3akDqBK4DcG97r2jWKYI1n0LQdUHEw_aem_F-kVG3LEqMQx8UnatShSEQ"
        entity_identifier: "div.x-container.max a"
        file_name: "agoradanse-events.jsonld"
        is_paginated: "false"
        headless: "false"