name: Score agoradanse.com Events

on:
  workflow_dispatch:
      
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/generate_report.yml
    with:
        page_url: "https://agoradanse.com/evenement/montreal-marrakech/"
        entity_identifier: "div.x-container.max a"
        file_name: "agoradanse-com.jsonld"
        is_paginated: "false"
        headless: "false"