name: Score centredesarts-ca Events

on:
  workflow_dispatch:
      
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/generate-report.yml
    with:
        page_url: "https://www.centredesarts.ca/programmation/"
        entity_identifier: "div.portfolio-text-title a"
        file_name: "centredesarts-ca.jsonld"
        is_paginated: "false"
        headless: "false"
        report-callback-url: "https://webhook.site/ffa29c57-3a09-4815-bfd3-2dc20bd4e0c7"
