name: Generate Score Report

on:
  workflow_dispatch:  # Can be triggered manually from GitHub Actions
    inputs:
      page_url:
        description: "The URL of the page to fetch JSON-LD data from"
        required: true
        type: string
      entity_identifier:
        description: "Identifier of the entity to fetch"
        required: true
        type: string
      file_name:
        description: "The name of the output file"
        required: true
        type: string
      is_paginated:
        description: "Is the page paginated? Set as 'true', 'false', or a page number"
        required: true
        type: string
      headless:
        description: "Run in headless mode ('true' or 'false')"
        required: true
        type: string

jobs:
  call-reusable-workflow:
    uses: culturecreates/artsdata-orion/.github/workflows/fetch-data.yml@main
    with:
      page_url: ${{ inputs.page_url }}
      entity_identifier: ${{ inputs.entity_identifier }}
      file_name: ${{ inputs.file_name }}
      is_paginated: ${{ inputs.is_paginated }}
      headless: ${{ inputs.headless }}
      save_method: 'artifact'

  download-and-commit-artifact:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: jsonld-data
        path: output/

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add "output/${{ inputs.file_name }}"
        git commit -m "Add json-ld fetched by the script"
        git push
  
  generate-report:
    runs-on: ubuntu-latest
    needs: download-and-commit-artifact
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run main script
      run: |
        bundle exec ruby src/main.rb \
        "https://raw.githubusercontent.com/culturecreates/artsdata-score/refs/heads/main/output/${{inputs.file_name}}"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        file_name="${{ inputs.file_name }}"
        base_name="${file_name%.jsonld}"
        git add "reports/${base_name}_report.csv"
        git commit -m "Add data generated by the script"
        git push
      

        
