name: Generate Score Report

on:
  workflow_dispatch:  # Can be triggered manually from GitHub Actions
    inputs:
      page-url:
        description: "URL of the webpage listing all events"
        required: true
        type: string
      entity-identifier:
        description: "CSS to identify individual event webpages (example: div.event-card a)"
        required: true
        type: string
      downloadFile:
        description: "File name"
        required: true
        type: string
      is-paginated:
        description: "Is the page paginated? (true|false|[page number])"
        required: true
        type: string
      headless:
        description: "Run in headless mode? (true|false)"
        required: true
        type: string

  workflow_call: 
    inputs:
      page-url:
        required: true
        type: string
      entity-identifier:
        required: true
        type: string
      downloadFile:
        required: true
        type: string
      is-paginated:
        required: true
        type: string
      headless:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true


jobs:
  call-reusable-workflow:
    uses: culturecreates/artsdata-pipeline-action@v2
    with:
      mode: fetch
      downloadFile:  ${{inputs.downloadFile}}
      page-url: ${{ inputs.page-url }}
      entity-identifier: ${{ inputs.entity-identifier }}
      is-paginated: ${{ inputs.is-paginated }}
      headless: ${{ inputs.headless }}
      token: ${{ secrets.GITHUB_TOKEN }}
      save-method: 'artifact'
  
  generate-report:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: jsonld-data
        path: output/

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run main script
      run: |
        bundle exec ruby src/main.rb \
        ${{inputs.file_name}}

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        file_name="${{ inputs.file_name }}"
        base_name="${file_name%.jsonld}"
        git add "reports/${base_name}_report.csv"
        git commit -m "Add data generated by the script"
        git push
      

        
