name: Score sandersoncentre.ca Events

on:
  workflow_dispatch:
 
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/generate_report.yml
    with:
        page-url: "https://calendar.sandersoncentre.ca/?page="
        entity-identifier: "div#CalendarList a.card"
        downloadFile: sandersoncentre-ca.jsonld
        is-paginated: true
        headless: true
        token: ${{ secrets.GITHUB_TOKEN }}